
# Extensive Dataset of Pakistani Keywords for AI Training

TRAINING_DATA = [
    # --- 1. FOOD & DINING ---
    ("Biryani", "Food & Dining"), ("Pulao", "Food & Dining"), ("Nihari", "Food & Dining"),
    ("Paya", "Food & Dining"), ("Haleem", "Food & Dining"), ("Karahi", "Food & Dining"),
    ("Sajji", "Food & Dining"), ("Chapli Kebab", "Food & Dining"), ("Seekh Kebab", "Food & Dining"),
    ("Tikka", "Food & Dining"), ("Malai Boti", "Food & Dining"), ("Chargha", "Food & Dining"),
    ("Katakat", "Food & Dining"), ("Brain Masala", "Food & Dining"), ("Maghaz", "Food & Dining"),
    ("Roti", "Food & Dining"), ("Naan", "Food & Dining"), ("Paratha", "Food & Dining"),
    ("Kulcha", "Food & Dining"), ("Sheermal", "Food & Dining"), ("Taftan", "Food & Dining"),
    ("Puri", "Food & Dining"), ("Halwa Puri", "Food & Dining"), ("Chana", "Food & Dining"),
    ("Pathura", "Food & Dining"), ("Bun Kebab", "Food & Dining"), ("Anday Wala Burger", "Food & Dining"),
    ("Gol Gappay", "Food & Dining"), ("Pani Puri", "Food & Dining"), ("Dahi Bhallay", "Food & Dining"),
    ("Chaat", "Food & Dining"), ("Samosa", "Food & Dining"), ("Pakora", "Food & Dining"),
    ("Roll Paratha", "Food & Dining"), ("Shawarma", "Food & Dining"), ("Zinger Burger", "Food & Dining"),
    ("Broast", "Food & Dining"), ("Pizza", "Food & Dining"), ("Fries", "Food & Dining"),
    ("Chai", "Food & Dining"), ("Tea", "Food & Dining"), ("Kashmiri Chai", "Food & Dining"),
    ("Green Tea", "Food & Dining"), ("Qahwa", "Food & Dining"), ("Doodh Patti", "Food & Dining"),
    ("Lassi", "Food & Dining"), ("Sardai", "Food & Dining"), ("Rabri", "Food & Dining"),
    ("Falooda", "Food & Dining"), ("Kulfi", "Food & Dining"), ("Gola Ganda", "Food & Dining"),
    ("Mithai", "Food & Dining"), ("Gulab Jamun", "Food & Dining"), ("Barfi", "Food & Dining"),
    ("Jalebi", "Food & Dining"), ("Laddu", "Food & Dining"), ("Sohan Halwa", "Food & Dining"),
    ("Cigarettes", "Food & Dining"), ("Cig", "Food & Dining"), ("Vape", "Food & Dining"),
    ("Tobacco", "Food & Dining"), ("Paan", "Food & Dining"), ("Naswar", "Food & Dining"),
    ("Gutka", "Food & Dining"), ("Sheesha", "Food & Dining"), ("Supari", "Food & Dining"),
    ("Grocery", "Food & Dining"), ("Atta", "Food & Dining"), ("Sugar", "Food & Dining"),
    ("Cheeni", "Food & Dining"), ("Rice", "Food & Dining"), ("Chawal", "Food & Dining"),
    ("Vegetables", "Food & Dining"), ("Sabzi", "Food & Dining"), ("Fruit", "Food & Dining"),
    ("Milk", "Food & Dining"), ("Doodh", "Food & Dining"), ("Yogurt", "Food & Dining"),
    ("Meat", "Food & Dining"), ("Gosht", "Food & Dining"), ("Chicken", "Food & Dining"),
    ("Mutton", "Food & Dining"), ("Beef", "Food & Dining"), ("Fish", "Food & Dining"),
    ("Masala", "Food & Dining"), ("Cooking Oil", "Food & Dining"), ("Dalda", "Food & Dining"), ("Mezan Oil", "Food & Dining"), ("Ghee", "Food & Dining"),
    ("Foodpanda", "Food & Dining"), ("Cheetay", "Food & Dining"), ("KFC", "Food & Dining"),
    ("McDonalds", "Food & Dining"), ("Subway", "Food & Dining"), ("Dominos", "Food & Dining"),
    ("Savour Foods", "Food & Dining"), ("Student Biryani", "Food & Dining"), ("Butt Karahi", "Food & Dining"),

    # --- 2. TRANSPORTATION ---
    ("Petrol", "Transportation"), ("Fuel", "Transportation"), ("Diesel", "Transportation"),
    ("CNG", "Transportation"), ("LPG", "Transportation"), ("High Octane", "Transportation"),
    ("Uber", "Transportation"), ("Careem", "Transportation"), ("Indrive", "Transportation"),
    ("Yango", "Transportation"), ("Bykea", "Transportation"), ("Taxi", "Transportation"),
    ("Rickshaw", "Transportation"), ("Chingchi", "Transportation"), ("Qingqi", "Transportation"),
    ("Auto", "Transportation"), ("Bus", "Transportation"), ("Metro", "Transportation"),
    ("Orange Line", "Transportation"), ("Speedo", "Transportation"), ("Green Line", "Transportation"),
    ("Red Line", "Transportation"), ("Daewoo", "Transportation"), ("Faisal Movers", "Transportation"),
    ("Niazi Express", "Transportation"), ("Skyways", "Transportation"), ("Bilal Travels", "Transportation"),
    ("Train Ticket", "Transportation"), ("Railway", "Transportation"), ("Pakistan Railway", "Transportation"),
    ("Flight", "Transportation"), ("PIA", "Transportation"), ("Airblue", "Transportation"),
    ("Serene Air", "Transportation"), ("Ticket", "Transportation"), ("Toll", "Transportation"),
    ("Toll Plaza", "Transportation"), ("M-Tag", "Transportation"), ("Motorway", "Transportation"),
    ("Challan", "Transportation"), ("Fine", "Transportation"), ("Parking", "Transportation"),
    ("Puncture", "Transportation"), ("Tyre Shop", "Transportation"), ("Mechanic", "Transportation"),
    ("Tuning", "Transportation"), ("Engine Oil", "Transportation"), ("Mobil Oil", "Transportation"), ("Car Oil", "Transportation"), ("Bike Oil", "Transportation"), ("Oil Change", "Transportation"),
    ("Service Station", "Transportation"), ("Driver Salary", "Transportation"),

    # --- 3. HOUSING & UTILITIES ---
    ("Rent", "Housing & Utilities"), ("Kiraya", "Housing & Utilities"), ("House Rent", "Housing & Utilities"),
    ("Electricity Bill", "Housing & Utilities"), ("Bijli Bill", "Housing & Utilities"),
    ("WAPDA", "Housing & Utilities"), ("LESCO", "Housing & Utilities"), ("KE", "Housing & Utilities"),
    ("K-Electric", "Housing & Utilities"), ("IESCO", "Housing & Utilities"), ("FESCO", "Housing & Utilities"),
    ("Gas Bill", "Housing & Utilities"), ("Sui Gas", "Housing & Utilities"), ("SNGPL", "Housing & Utilities"),
    ("SSGC", "Housing & Utilities"), ("Cylinder", "Housing & Utilities"),
    ("Water Bill", "Housing & Utilities"), ("Water Tanker", "Housing & Utilities"), ("Paani", "Housing & Utilities"),
    ("Internet", "Housing & Utilities"), ("Wifi", "Housing & Utilities"), ("PTCL", "Housing & Utilities"),
    ("Stormfiber", "Housing & Utilities"), ("Nayatel", "Housing & Utilities"), ("Transworld", "Housing & Utilities"),
    ("Fiberlink", "Housing & Utilities"), ("Cable TV", "Housing & Utilities"),
    ("Maid Salary", "Housing & Utilities"), ("Kaam Wali", "Housing & Utilities"), ("Sweeper", "Housing & Utilities"),
    ("Guard Salary", "Housing & Utilities"), ("Chowkidar", "Housing & Utilities"),
    ("Plumber", "Housing & Utilities"), ("Electrician", "Housing & Utilities"), ("Carpenter", "Housing & Utilities"),
    ("Repair", "Housing & Utilities"), ("Maintenance", "Housing & Utilities"), ("Furniture", "Housing & Utilities"),

    # --- 4. MOBILE & COMMUNICATION ---
    ("Easyload", "Mobile & Communication"), ("Balance", "Mobile & Communication"),
    ("Topup", "Mobile & Communication"), ("Recharge", "Mobile & Communication"),
    ("Super Card", "Mobile & Communication"), ("Package", "Mobile & Communication"),
    ("Bundle", "Mobile & Communication"), ("Jazz", "Mobile & Communication"),
    ("Zong", "Mobile & Communication"), ("Telenor", "Mobile & Communication"),
    ("Ufone", "Mobile & Communication"), ("Onic", "Mobile & Communication"),
    ("Sim Card", "Mobile & Communication"), ("PTA Tax", "Mobile & Communication"),

    # --- 5. SHOPPING ---
    ("Clothes", "Shopping"), ("Kapray", "Shopping"), ("Suit", "Shopping"),
    ("Kurta", "Shopping"), ("Shalwar Kameez", "Shopping"), ("Unstitched", "Shopping"),
    ("Pret", "Shopping"), ("Lawn", "Shopping"), ("Winter", "Shopping"),
    ("Khaadi", "Shopping"), ("Sapphire", "Shopping"), ("Gul Ahmed", "Shopping"),
    ("Limelight", "Shopping"), ("J.", "Shopping"), ("Junaid Jamshed", "Shopping"),
    ("Alkaram", "Shopping"), ("Nishat", "Shopping"), ("Sana Safinaz", "Shopping"),
    ("Bonanza", "Shopping"), ("Outfitters", "Shopping"), ("Breakout", "Shopping"),
    ("Shoes", "Shopping"), ("Jootay", "Shopping"), ("Bata", "Shopping"),
    ("Service", "Shopping"), ("Hush Puppies", "Shopping"), ("Ndure", "Shopping"),
    ("Borjan", "Shopping"), ("Stylo", "Shopping"), ("Metro Shoes", "Shopping"),
    ("Bags", "Shopping"), ("Handbag", "Shopping"), ("Wallet", "Shopping"),
    ("Makeup", "Shopping"), ("Cosmetics", "Shopping"), ("Perfume", "Shopping"),
    ("Attar", "Shopping"), ("Watch", "Shopping"), ("Sunglasses", "Shopping"),
    ("Daraz", "Shopping"), ("Online Shopping", "Shopping"), ("Parcel", "Shopping"),
    ("Sunday Bazar", "Shopping"), ("Landay", "Shopping"), ("Landa Bazar", "Shopping"),

    # --- 6. HEALTH & FITNESS ---
    ("Doctor", "Health & Fitness"), ("Consultation", "Health & Fitness"), ("Fee", "Health & Fitness"),
    ("Hospital", "Health & Fitness"), ("Clinic", "Health & Fitness"), ("Emergency", "Health & Fitness"),
    ("Medicine", "Health & Fitness"), ("Dawai", "Health & Fitness"), ("Pharmacy", "Health & Fitness"),
    ("Medical Store", "Health & Fitness"), ("Panadol", "Health & Fitness"), ("Antibiotic", "Health & Fitness"),
    ("Syrup", "Health & Fitness"), ("Injection", "Health & Fitness"),
    ("Lab Test", "Health & Fitness"), ("Blood Test", "Health & Fitness"), ("Ultrasound", "Health & Fitness"),
    ("X-Ray", "Health & Fitness"), ("MRI", "Health & Fitness"), ("Chughtai Lab", "Health & Fitness"),
    ("Gym", "Health & Fitness"), ("Fitness", "Health & Fitness"), ("Workout", "Health & Fitness"),
    ("Yoga", "Health & Fitness"), ("Protein", "Health & Fitness"), ("Supplements", "Health & Fitness"),
    ("Barber", "Health & Fitness"), ("Haircut", "Health & Fitness"), ("Salon", "Health & Fitness"),
    ("Beauty Parlor", "Health & Fitness"), ("Facial", "Health & Fitness"),

    # --- 7. EDUCATION ---
    ("School Fee", "Education"), ("College Fee", "Education"), ("University Fee", "Education"),
    ("Semester Fee", "Education"), ("Admission Fee", "Education"), ("Exam Fee", "Education"),
    ("Tuition", "Education"), ("Academy", "Education"), ("Qari Sahib", "Education"),
    ("Books", "Education"), ("Book", "Education"), ("Notebooks", "Education"), ("Stationery", "Education"),
    ("Pen", "Education"), ("Pencil", "Education"), ("Uniform", "Education"),
    ("Photocopies", "Education"), ("Photocopy", "Education"), ("Prints", "Education"), ("Notes", "Education"),
    ("Course", "Education"), ("Training", "Education"), ("Workshop", "Education"),

    # --- 8. ENTERTAINMENT ---
    ("Movie", "Entertainment"), ("Cinema", "Entertainment"), ("Film", "Entertainment"),
    ("Netflix", "Entertainment"), ("Spotify", "Entertainment"), ("Youtube Premium", "Entertainment"),
    ("Amazon Prime", "Entertainment"), ("Disney", "Entertainment"),
    ("Gaming", "Entertainment"), ("PS5", "Entertainment"), ("Xbox", "Entertainment"),
    ("Steam", "Entertainment"), ("Pubg", "Entertainment"), ("UC", "Entertainment"),
    ("Picnic", "Entertainment"), ("Trip", "Entertainment"), ("Tour", "Entertainment"),
    ("Ticket", "Entertainment"), ("Concert", "Entertainment"), ("Event", "Entertainment"),
    ("Bowling", "Entertainment"), ("Joyland", "Entertainment"), ("Park", "Entertainment"),

    # --- 9. GIFTS & DONATIONS ---
    ("Gift", "Gifts & Donations"), ("Present", "Gifts & Donations"), ("Birthday", "Gifts & Donations"),
    ("Anniversary", "Gifts & Donations"), ("Wedding", "Gifts & Donations"), ("Shadi", "Gifts & Donations"),
    ("Salami", "Gifts & Donations"), ("Eidi", "Gifts & Donations"),
    ("Donation", "Gifts & Donations"), ("Zakat", "Gifts & Donations"), ("Sadqa", "Gifts & Donations"),
    ("Khairat", "Gifts & Donations"), ("Fitrana", "Gifts & Donations"), ("Charity", "Gifts & Donations"),
    ("Mosque", "Gifts & Donations"), ("Masjid", "Gifts & Donations"), ("Madrasa", "Gifts & Donations"),
    ("Beggar", "Gifts & Donations"), ("Help", "Gifts & Donations"),

    # --- 10. FINANCIAL / OTHERS ---
    ("Bank", "Financial / Others"), ("Charges", "Financial / Others"), ("Tax", "Financial / Others"),
    ("WHT", "Financial / Others"), ("FED", "Financial / Others"),
    ("Insurance", "Financial / Others"), ("Premium", "Financial / Others"),
    ("Committee", "Financial / Others"), ("BC", "Financial / Others"), ("Installment", "Financial / Others"),
    ("Loan", "Financial / Others"), ("Debt", "Financial / Others"), ("Udhaar", "Financial / Others"),
    ("Gold", "Financial / Others"), ("Investment", "Financial / Others"), ("Saving", "Financial / Others")
]
